django_movie/django_movie/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include("movies.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_movie/movies/urls.py
from django.urls import path

from . import views


urlpatterns = [
    # name для вставки в html {% url 'movie_detail' %}
    path("", views.MoviesView.as_view(), name='movies'),
    # Размещён перед шаблоном поиском фильма по слагу чтобы не было ошибки с переменной queryset
    # url - для фильтра фильмов по году или жанру
    path("filter/", views.FilterMoviesView.as_view(), name='filter'),
    path("add-rating/", views.AddStarRating.as_view(), name='add_rating'),
    # path("json-filter/", views.JsonFilterMoviesView.as_view(), name="json_filter"),
    path("<slug:slug>/", views.MovieDetailView.as_view(), name="movie_detail"),
    path("review/<int:pk>/", views.AddReview.as_view(), name="add_review"),
    path("actor/<str:slug>/", views.ActorView.as_view(), name="actor_detail"),
]

django_movie/movies/models.py
from datetime import date

from django.db import models
from django.urls import reverse


class Category(models.Model):
    """Категории"""
    name = models.CharField("Категория", max_length=150)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    # Контейнер класса с метаданными
    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Actor(models.Model):
    """Актёры и режиссёры"""
    name = models.CharField("Имя", max_length=100)
    age = models.PositiveSmallIntegerField("Возраст", default=0)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="actors/")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('actor_detail', kwargs={'slug':self.name})

    class Meta:
        verbose_name = "Актёры и режиссёры"
        verbose_name_plural = "Актёры и режиссёры"


class Genre(models.Model):
    """Жанры"""
    name = models.CharField("Имя", max_length=100)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанры"


class Movie(models.Model):
    """Фильмы"""
    title = models.CharField("Название", max_length=100)
    tagline = models.CharField("Слоган", max_length=100, default='')
    description = models.TextField("Описание")
    poster = models.ImageField("Постер", upload_to="movies/")
    # PositiveSmallIntegerField() положительное целочисленное значение (от 0 до 32767)
    # SmallIntegerField(): хранит значение типа Number (от -32768 до 32767)
    year = models.PositiveSmallIntegerField("Дата выхода", default=2023)
    country = models.CharField("Страна", max_length=30)
    # related_name - позволяет обращаться из связанных объектов к тем, от которых эта связь была создана.
    directors = models.ManyToManyField(Actor, verbose_name="режиссёр", related_name="film_director")
    actors = models.ManyToManyField(Actor, verbose_name="актёры", related_name="film_actor")
    genres = models.ManyToManyField(Genre, verbose_name="жанры")
    world_premiere = models.DateField("Премьера в мире", default=date.today)
    # PositiveIntegerField(): хранит значение типа Number, которое представляет
    # положительное целочисленное значение (от 0 до 2147483647)
    # help_text - справочный текст для отображения в виджетах формы.
    budget = models.PositiveIntegerField("Бюджет", default=0, help_text="указывать сумму в долларах")
    fees_in_usa = models.PositiveIntegerField(
        "Сборы в США", default=0, help_text="указывать сумму в долларах"
    )
    fees_in_world = models.PositiveIntegerField(
        "Сборы в мире", default=0, help_text="указывать сумму в долларах"
    )
    category = models.ForeignKey(
        Category, verbose_name="Категория", on_delete=models.SET_NULL, null=True
    )
    #  slug – это уникальный фрагмент URL-адреса, ассоциированный с конкретной записью и, обычно,
    #  состоит из набора маленьких латинских букв, цифр, символов подчёркивания и дефиса.
    url = models.SlugField(max_length=160, unique=True)
    draft = models.BooleanField("Черновик", default=False)

    def __str__(self):
        return self.title

    def get_review(self):
        """Возвращает список связанных коментариев у
        которых отсутствует родитель."""
        return self.reviews_set.filter(parent__isnull=True)

    def get_absolute_url(self):
        """ Будет возвращать метод реверс в который мы передаём имя url-адреса,
         и в словаре передаём параметры которые необходимо передать в url (slug),
         ключём будет 'slug': а значением данные поля url модели."""

        # A первым параметром передаём имя url-адреса : "movie_detail".
        return reverse("movie_detail", kwargs={"slug": self.url})

    class Meta:
        verbose_name = "Фильм"
        verbose_name_plural = "Фильмы"


class MovieShots(models.Model):
    """Кадры из фильма"""
    title = models.CharField("Заголовок", max_length=100)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="movie_shots/")
    movie = models.ForeignKey(Movie, verbose_name="Фильм", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Кадр из фильма"
        verbose_name_plural = "Кадры из фильма"


class RatingStar(models.Model):
    """Звезда рейтинга"""
    value = models.SmallIntegerField("Значение", default=0)

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = "Звезда рейтинга"
        verbose_name_plural = "Звезды рейтинга"
        ordering = ["-value"]


class Rating(models.Model):
    """Рейтинг"""
    ip = models.CharField("IP адрес", max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name="звезда")
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name="фильм")

    def __str__(self):
        return f"{self.star} - {self.movie}"

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"


class Reviews(models.Model):
    """Отзывы"""
    email = models.EmailField()
    name = models.CharField("Имя", max_length=100)
    text = models.TextField("Сообщение", max_length=5000)
    parent = models.ForeignKey(
        # 'self' - указывает что запись будет ссылаться на запись в этой же таблице.
        'self', verbose_name="Родитель", on_delete=models.SET_NULL, blank=True, null=True
    )
    movie = models.ForeignKey(Movie, verbose_name="фильм", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.movie}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

django_movie/movies/forms.py
from django import forms

from .models import Reviews, RatingStar, Rating


# Если необходимо указывать в форме поля не связанные с моделями то наследуемся от forms
class ReviewForm(forms.ModelForm):
    """Форма отзывов"""
    class Meta:
        model = Reviews
        fields = ("name", "email", "text")


class RatingForm(forms.ModelForm):
    """Форма добавления рейтинга"""
    # Переопределяем поле star и с помощью ModelChoiceField передаём в него все экземпляры модели
    # RatingStar и виджет - радиокнопку (или можно выбрать выпадающий список или чекбокс)
    star = forms.ModelChoiceField(
        queryset=RatingStar.objects.all(), widget=forms.RadioSelect(), empty_label=None
    )

    class Meta:
        model = Rating
        fields = ("star",)

django_movie/movies/views.py
from django.db.models import Q
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.base import View

from .models import Movie, Category, Actor, Genre, Rating
from . forms import ReviewForm, RatingForm


class GenreYears:
    """ Жанры и года"""

    def get_genres(self):
        return Genre.objects.all()

    def get_years(self):
        # Функция values возвращает указанные словари, values_list кортежи
        return Movie.objects.filter(draft=False).values("year")


class MoviesView(GenreYears, ListView):
    """Список фильмов"""
    model = Movie
    queryset = Movie.objects.filter(draft=False)
    # Шаблон не указывается потому-что Джанго ищет шаблон по имени модели добавляя к нему _list
    # template_name = "movies/movies.html"

    # # Для того чтобы на странице списка фильмов дополнительно вывести категории необходимо добавить метод
    # # get_context_data
    # def get_context_data(self, *args, **kwargs):
    #     # Вызываем метод super() родителя, таким образом мы получаем словарь и заносим его в реременную context
    #     context = super().get_context_data(*args, **kwargs)
    #     # Добавляем в него ключ 'categories' и заносим в него queryset всех наших категорий
    #     context['categories'] = Category.objects.all()
    #     return context


class MovieDetailView( GenreYears, DetailView):
    """Полное описание фильма"""
    model = Movie
    # Отвечает за поле по которому будет происходить поиск записи,
    # сравнивая с данными переданными из url
    slug_field = "url"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["star_form"] = RatingForm()
        return context
    # Шаблон неуказывается потому-что Джанго ищет шаблон по имени модели добавляя к нему "_detail"
    # Можно указать явно через template_name

    # # Для того чтобы на странице фильма дополнительно вывести категории необходимо добавить метод
    # # get_context_data
    # def get_context_data(self, *args, **kwargs):
    #     # Вызываем метод super() родителя, таким образом мы получаем словарь и заносим его в реременную context
    #     context = super().get_context_data(*args, **kwargs)
    #     # Добавляем в него ключ 'categories' и заносим в него queryset всех наших категорий
    #     context['categories'] = Category.objects.all()
    #     return context


class AddReview(View):
    """Отзывы"""
    def post(self, request, pk):
        # В созданную форму передаём данные из post запроса
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(id=pk)
        if form.is_valid():
            # Так как отзыв мы привязываем к опред-ому фильму, необходимо указать к какому фильму будет привязан отзыв

            # Вызывая у формы метод save и передавая commit=False, приостанавливаем сохранение фармы, чтобы внести изменения
            form = form.save(commit=False)
            # Если в пост запроссе есть ключь "parent", тоесть если отроботал скрипт ответа на коментарий и в поле
            # "parent" подставлено значение
            if request.POST.get("parent", None):
                # Полю формы parent_id присваиваем числовое значение поля parent
                form.parent_id = int(request.POST.get("parent"))

            # В поле movie_id передаём pk из запроса (ForeignKey), чтобы при сохранении формы
            # создать запись Reviews в бд и привязать её к фильму
            # form.movie_id = pk

            form.movie = movie

            form.save()

        # Функция get_absolute_url() - вернёт шаблон movie_detail со слагом текущей модели movie
        return redirect(movie.get_absolute_url())


class ActorView(GenreYears, DetailView):
    """ Вывод информации о актёре. """
    model = Actor
    template_name = "movies/actor.html"
    # Поле по которому мы будем искать актёров
    slug_field = "name"


class FilterMoviesView(GenreYears, ListView):
    """Фильтр фильмов"""
    def get_queryset(self):
        # getlist - выбрать все зночения атрибута
        queryset = Movie.objects.filter(Q(year__in=self.request.GET.getlist("year")) |
                                        Q(genres__in=self.request.GET.getlist("genre")))
        return queryset


class JsonFilterMoviesView(ListView):
    """Фильтр фильмов в json"""

    def get_queryset(self):
        queryset = Movie.objects.filter(
            Q(year__in=self.request.GET.getlist("year")) |
            Q(genres__in=self.request.GET.getlist("genre"))
        ).distinct().values("title", "tagline", "url", "poster")  # Метод disctinсt выбирает уникальные значения
        return queryset

    def get(self, request, *args, **kwargs):
        queryset = list(self.get_queryset())
        return JsonResponse({"movies": queryset}, safe=False)


class AddStarRating(View):
    """Добавление рейтинга фильму"""


    def get_client_ip(self, request):
        # HTTP_X_FORWARDED_FOR — содержит цепочку прокси адресов и последним идёт IP
        # непосредственного клиента обратившегося к прокси серверу
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

    def post(self, request):
        # Когда приходит пост запрос, передаём в форму запрас
        form = RatingForm(request.POST)

        if form.is_valid():
            # Проверяем экземпляры классов Rating по полям: ip, movie_id. И обновляем (поле defaults)
            # те привяжемся к другой звезде, или создаём новую запись RatingStar.
            Rating.objects.update_or_create(
                ip=self.get_client_ip(request),
                movie_id=int(request.POST.get("movie")),
                defaults={'star_id': int(request.POST.get("star"))}
            )
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)

django_movie/templates/movies/actor.html
{% extends 'movies/base.html' %}
{% load static %}
{% block header %} bg2 {% endblock header %}
{% block title %} {{ actor.name }} {% endblock title %}

{% block container %}
<div class="container py-md-3">
  {% endblock container %}

  {% block sidebar %}
  <div class="side-bar col-lg-4">
    {% endblock sidebar %}

    {% block movie %}

    <div class="left-ads-display col-lg-8">

        <div class="desc1-left col-md-6">
          <img src="{{ actor.image.url }}" class="img-fluid" alt="">
        </div>
        <div class="desc1-right col-md-6 pl-lg-4">
          <h3 class="editContent" style="outline: none; cursor: inherit;">
            {{ actor.name }}
          </h3>
          <h5 class="editContent"></h5>
          <div>
            <li style="list-style: none"><span><b>Возраст:</b>
                                    {{ actor.age }}
                                </span></li>

            <li style="list-style: none">
                                    <span><b>Режиссер:</b>
                                      <!--  Чтобы узноть в каких фильмах был режиссёром используем
                                        related_name модели Movie (film_director)-->
                                        {% for movie in actor.film_director.all %}
                                            {{ movie.title }}
                                        {% endfor %}
                                    </span>
            </li>
            <li style="list-style: none">
                                    <span><b>Актер:</b>
                                      <!--  Чтобы узноть в каких фильмах был актёром используем
                                        related_name модели Movie (film_actor)-->
                                        {% for movie in actor.film_actor.all %}
                                            {{ movie.title }}
                                        {% endfor %}
                                    </span>
            </li>


          </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">

          <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
            О {{ actor.name }}</h3>

          <p class="editContent" >
          <!-- Тег safe служит для того чтобы теги добавленные через ckeditor выводились не как текст а
                рендерелись вместе с шаблоном -->
            {{ actor.description|safe }}
          </p>

        </div>


    </div>
    {% endblock movie %}
  </div>
</div>

django_movie/templates/movies/base.html
{% extends 'base.html' %}

{% block content %}
<section class="ab-info-main py-md-5 py-4 editContent" style="padding-left: 3rem; padding-right: 3rem;">

  {% block container %}
  <div class="container-fluid py-md-3">
    {% endblock container %}

    <div class="row">

      {% block sidebar %}
      <div class="side-bar col-lg-3">
        {% endblock sidebar %}

        {% include 'include/sidebar.html' %}
      </div>
      {% block movie %}
      {% endblock movie %}

    </div>
  </div>
</section>
{% endblock content %}

django_movie/templates/movies/movie_detail.html
{% extends 'movies/base.html' %}
{% load static %}
{% block header %} bg2 {% endblock header %}
{% block title %} {{ movie.title }} {% endblock title %}

{% block container %}
<div class="container py-md-3">
  {% endblock container %}

  {% block sidebar %}
  <div class="side-bar col-lg-4">
    {% endblock sidebar %}

    {% block movie %}

    <div class="left-ads-display col-lg-8">
      <ul class="row">
        <div class="desc1-left col-md-6">
          <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
        </div>
        <div class="desc1-right col-md-6 pl-lg-4">
          <h3 class="editContent" style="outline: none; cursor: inherit;">
            {{ movie.title }}
          </h3>
          <h5 class="editContent"></h5>
          <div>
            <li style="list-style: none"><span><b>Год:</b>
                                    {{ movie.year }}
                                </span></li>
            <li style="list-style: none"><span><b>Страна:</b>
                                    {{ movie.country }}
                                </span>
            </li>
            <li style="list-style: none"><span><b>Слоган:</b>
                                    {{ movie.tagline }}
                                </span>
            </li>
            <li style="list-style: none">
                                    <span><b>Режиссер:</b>
                                        {% for director in movie.directors.all %}
                                        <!--  Добавляем ссылку (прописываем имя url адреса и slug для него.  -->
<!--                                           <a href="{% url 'actor_detail' actor.name ">{{ director.name </a>-->
                                          <a href="{{ director.get_absolute_url }}">{{ director.name }}</a>
                                        {% endfor %}
                                    </span>
            </li>
            <li style="list-style: none">
                                    <span><b>Актеры:</b>
                                        {% for actor in movie.actors.all %}

                                            <!--  Добавляем ссылку (прописываем имя url адреса и slug для него.  -->
<!--                                      <a href="{% url 'actor_detail' actor.name ">{{ actor.name </a>-->
                                          <a href="{{ actor.get_absolute_url }}">{{ actor.name }}</a>
                                        {% endfor %}
                                    </span>
            </li>
            <li style="list-style: none">
                                    <span><b>Жанр:</b>
                                        {% for genre in movie.genres.all %}
                                            {{ genre.name }}
                                        {% endfor %}
                                    </span>
            </li>
            <li style="list-style: none"><span><b>Премьера в мире:</b> {{ movie.world_premiere }} </span>
            </li>
            <li style="list-style: none">
              <span><b>Бюджет:</b> ${{ movie.budget }} </span></li>
            <li style="list-style: none">
              <span><b>Сборы в США:</b> ${{ movie.fees_in_usa }} </span></li>
            <li style="list-style: none">
                                    <span><b>Сборы в мире:</b>
                                        ${{ movie.fees_in_world }}
                                    </span>
            </li>
            <li>
              <form action="{% url 'add_rating' %}" method="post" name="rating">
                <b>Рейтинг:</b>
                {% csrf_token %}
                <input type="hidden" value="{{ movie.id }}" name="movie">
                <span class="rating">

                  {% for k, v in star_form.fields.star.choices %}
                    <input id="rating{{ v }}" type="radio" name="star"
                          value="{{ k }}">
                    <label for="rating{{ v }}">{{ k }}</label>
                  {% endfor %}
                </span>

                <span class="editContent">4.0</span>
              </form>
            </li>
            <div class="share-desc">
              <div class="share">
                <h4 class="editContent"
                    style="outline: none; cursor: inherit;">
                  Share:</h4>
                <ul class="w3layouts_social_list list-unstyled">
                  <li>
                    <a href="#" class="w3pvt_facebook editContent"
                       style="outline: none; cursor: inherit;">
                                                <span class="fa fa-facebook-f"
                                                      style="outline: none; cursor: inherit;"></span>
                    </a>
                  </li>
                  <li>
                    <a href="#" class="w3pvt_twitter editContent"
                       style="outline: none; cursor: inherit;">
                                                <span class="fa fa-twitter"
                                                      style="outline: none; cursor: inherit;"></span>
                    </a>
                  </li>
                  <li>
                    <a href="#" class="w3pvt_dribble editContent"
                       style="outline: none; cursor: inherit;">
                                                <span class="fa fa-dribbble"
                                                      style="outline: none; cursor: inherit;"></span>
                    </a>
                  </li>
                </ul>
              </div>
              <div class="clearfix"></div>
            </div>
          </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">

          <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
            О фильме {{ movie.title }}</h3>
          <p>
            {% for image in movie.movieshots_set.all %}
            <img src="{{ image.image.url }}" class="img-fluid img-movie-shots" alt="{{ image.description }}">
            {% endfor %}
          </p>
          <p class="editContent" style="outline: none; cursor: inherit;">
          <!-- Тег safe служит для того чтобы теги добавленные через ckeditor выводились не как текст а
                рендерелись вместе с шаблоном -->
            {{ movie.description|safe }}
          </p>
<!--          <p class="mt-3 italic-blue editContent"-->
<!--             style="outline: none; cursor: inherit;">-->
<!--            <iframe width="560" height="315"-->
<!--                    src="https://www.youtube.com/embed/A36LahZNUiE?controls=0"-->
<!--                    frameborder="0" allow="accelerometer; autoplay;-->
<!--                                                                           encrypted-media; gyroscope; picture-in-picture"-->
<!--                    allowfullscreen>-->

<!--            </iframe>-->
<!--          </p>-->

        </div>
        <hr>
        <div class="row">
          <div class="single-form-left">
            <!-- contact form grid -->
            <div class="contact-single">
              <h3 class="editContent">
                                    <span class="sub-tittle editContent"
                                          style="outline: none; cursor: inherit;">{{ movie.reviews_set.count }}</span>Оставить
                отзыв</h3>
              <!--  В актион прописываем url адрес на форму  -->
              <form action="{% url 'add_review' movie.id %}" method="post" class="mt-4" id="formReview">
                {% csrf_token %}

                <!--            Скрытое поле ввода, в нём будем передавать id комментария на который
                                  хотим ответить (родителя), -->
                <input type="hidden" name="parent" id="contactparent" value="">

                <div class="form-group editContent">
                  <label for="contactcomment" class="editContent">
                    Ваш комментарий *
                  </label>

                  <!--              Зночения полей name - это ключи для передаваемых данных post-запросом  -->

                  <textarea class="form-control border" rows="5" name="text"
                            id="contactcomment" required=""></textarea>
                </div>
                <div class="d-sm-flex">
                  <div class="col-sm-6 form-group p-0 editContent">
                    <label for="contactusername" class="editContent">
                      Имя *
                    </label>
                    <input type="text" class="form-control border" name="name"
                           id="contactusername" required="">
                  </div>
                  <div class="col-sm-6 form-group ml-sm-3 editContent">
                    <label for="contactemail" class="editContent">
                      Email *
                    </label>
                    <input type="email" class="form-control border" name="email"
                           id="contactemail" required="">
                  </div>
                </div>
                <button type="submit"
                        class="mt-3 btn btn-success btn-block py-3">
                  Отправить
                </button>
              </form>
            </div>
            <!--  //contact form grid ends here -->
          </div>

          <!--        Вызываем функцию get_review модели Movies получаем список связанных коментариев-->
          {% for review in movie.get_review %}
          <div class="media py-5">
            <img src="{% static 'images/te2.jpg' %}" class="mr-3 img-fluid" alt="image"
                 style="outline: none; cursor: inherit;">
            <div class="media-body mt-4">
              <h5 class="mt-0 editContent"
                  style="outline: none; cursor: inherit;">
                {{ review.name }}
              </h5>
              <p class="mt-2 editContent" style="outline: none; cursor: inherit;">
                {{ review.text }}

              </p>

              <!--          Ссылка для ответа на отзыв, onclick="addReview()" - передаём имя и id пользователя на чей комент
                              хотим ответить в функцию javascript -->

              <a href="#formReview" onclick="addReview('{{ review.name }}', '{{ review.id }}')">Ответить</a>

              <!--          Получаем список ответов связанный с данным коментарием    -->
              {% for rev in review.reviews_set.all %}
              <div class="media mt-5 editContent"
                   style="outline: none; cursor: inherit;">
                <a class="pr-3" href="#">
                  <img src="{% static 'images/te1.jpg' %}" class="img-fluid "
                       alt="image" style="outline: none; cursor: inherit;">
                </a>
                <div class="media-body">
                  <h5 class="mt-0 editContent"
                      style="outline: none; cursor: inherit;">{{ rev.name }}</h5>
                  <p class="mt-2 editContent"
                     style="outline: none; cursor: inherit;">
                    {{ rev.text }}
                  </p>
                </div>
              </div>
              {% endfor %}

            </div>
          </div>
          {% endfor %}
        </div>
      </ul>
    </div>
    <script>
        <!--          В id - будет присваиваться значение для поля parent, а в name - имя автора родительского сообщ.     -->
        function addReview(name, id) {
            document.getElementById("contactparent").value = id;
            document.getElementById("contactcomment").innerText = `${name}, `
        }
    </script>
    {% endblock movie %}
  </div>
</div>

django_movie/templates/movies/movie_list.html
{% extends 'movies/base.html' %}

{% block header %} bg1 {% endblock header %}

{% block movie %}
<div class="left-ads-display col-lg-9">
  <div class="row">
    {% for movie in movie_list %}
    <div class="col-md-4 product-men">
      <div class="product-shoe-info editContent text-center mt-lg-4">
        <div class="men-thumb-item">
          <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
        </div>
        <div class="item-info-product">
          <h4 class="">

            <!-- Вызываем метод get_absolute_url модели movie -->

            <a href=" {{ movie.get_absolute_url }} " class="editContent">

              {{ movie.title }}
            </a>
          </h4>

          <div class="product_price">
            <div class="grid-price">
              <span class="money editContent">{{ movie.tagline }}</span>
            </div>
          </div>
          <ul class="stars">
            <li><a href="#"><span class="fa fa-star" aria-hidden="true"></span></a></li>
            <li><a href="#"><span class="fa fa-star" aria-hidden="true"></span></a></li>
            <li><a href="#"><span class="fa fa-star-half-o" aria-hidden="true"></span></a></li>
            <li><a href="#"><span class="fa fa-star-half-o" aria-hidden="true"></span></a></li>
            <li><a href="#"><span class="fa fa-star-o" aria-hidden="true"></span></a></li>
          </ul>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <!--<div class="grid-img-right mt-4 text-right bg bg1" >
      <span class="money editContent" >Flat 50% Off</span>
      <a href="moviesingle.html" class="btn" >Now</a>
  </div>-->
</div>

{% endblock movie %}